# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Khalif/factorial/factorial.cache/wt [current_project]
set_property parent.project_path C:/Users/Khalif/factorial/factorial.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/Alu.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/Mux.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/Dreg.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/comparater.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/Ud_Cnt_4.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/bcd_to_7seg.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/Factorial_DP.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/Factorial_CU.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/showNumber.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/led_mux.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/clk_gen.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/button_debouncer.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/bin2bcd32.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/Factorial.v
  C:/Users/Khalif/factorial/factorial.srcs/sources_1/new/Factorial_fpga.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Khalif/factorial/factorial.srcs/constrs_1/new/factorial_fpga.xdc
set_property used_in_implementation false [get_files C:/Users/Khalif/factorial/factorial.srcs/constrs_1/new/factorial_fpga.xdc]


synth_design -top Factorial_fpga -part xc7a100tcsg324-2


write_checkpoint -force -noxdef Factorial_fpga.dcp

catch { report_utilization -file Factorial_fpga_utilization_synth.rpt -pb Factorial_fpga_utilization_synth.pb }
