# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Anahit Sarao/Desktop/cmpe125labs/lab3/lab3.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Anahit Sarao/Desktop/cmpe125labs/lab3/lab3.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Anahit Sarao/Desktop/cmpe125labs/lab3/lab3.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Anahit Sarao/Desktop/cmpe125labs/lab3/lab3.srcs/sources_1/new/decoder_case.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Anahit Sarao/Desktop/cmpe125labs/lab3/lab3.srcs/constrs_1/imports/Desktop/pri_encoder_fpga.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Anahit Sarao/Desktop/cmpe125labs/lab3/lab3.srcs/constrs_1/imports/Desktop/pri_encoder_fpga.xdc}}]


synth_design -top decoder_case -part xc7a100tcsg324-1


write_checkpoint -force -noxdef decoder_case.dcp

catch { report_utilization -file decoder_case_utilization_synth.rpt -pb decoder_case_utilization_synth.pb }
