# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Nhu/140 labs/SOC/SOC.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Nhu/140 labs/SOC/SOC.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Nhu/140 labs/SOC/SOC.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {{C:/Users/Nhu/140 labs/SOC/SOC.srcs/sources_1/new/memfile.dat}}
read_verilog -library xil_defaultlib {
  {C:/Users/Nhu/140 labs/SOC/SOC.srcs/sources_1/new/MIPS.v}
  {C:/Users/Nhu/140 labs/SOC/SOC.srcs/sources_1/new/GPIO.v}
  {C:/Users/Nhu/140 labs/SOC/SOC.srcs/sources_1/new/fact.v}
  {C:/Users/Nhu/140 labs/SOC/SOC.srcs/sources_1/new/utility.v}
  {C:/Users/Nhu/140 labs/SOC/SOC.srcs/sources_1/new/SOC_decoder.v}
  {C:/Users/Nhu/140 labs/SOC/SOC.srcs/sources_1/new/fpga.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Nhu/140 labs/SOC/SOC.srcs/constrs_1/new/SOC_FPGA.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Nhu/140 labs/SOC/SOC.srcs/constrs_1/new/SOC_FPGA.xdc}}]


synth_design -top SoC_fpga -part xc7a100tcsg324-1


write_checkpoint -force -noxdef SoC_fpga.dcp

catch { report_utilization -file SoC_fpga_utilization_synth.rpt -pb SoC_fpga_utilization_synth.pb }
